In [19]:
pip install yfinance

Requirement already satisfied: yfinance in /opt/conda/lib/python3.7/site-packages (0.1.60)
Requirement already satisfied: pandas>=0.24 in /opt/conda/lib/python3.7/site-packages (from yfinance) (1.2.2)
Requirement already satisfied: requests>=2.20 in /opt/conda/lib/python3.7/site-packages (from yfinance) (2.25.1)
Requirement already satisfied: lxml>=4.5.1 in /opt/conda/lib/python3.7/site-packages (from yfinance) (4.6.3)
Requirement already satisfied: numpy>=1.15 in /opt/conda/lib/python3.7/site-packages (from yfinance) (1.19.5)
Requirement already satisfied: multitasking>=0.0.7 in /opt/conda/lib/python3.7/site-packages (from yfinance) (0.0.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.24->yfinance) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.24->yfinance) (2021.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance) (1.15.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /opt/conda/lib/python3.7/site-packages (from requests>=2.20->yfinance) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests>=2.20->yfinance) (1.26.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests>=2.20->yfinance) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests>=2.20->yfinance) (2.10)
Note: you may need to restart the kernel to use updated packages.

In [20]:
import numpy as np
import pandas as pd

In [21]:
BTC_price = yf.download(tickers='BTC-USD', period = '30d', interval = '15m')
BTC_price

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-06-08 00:00:00+01:00,34195.167969,34195.167969,34095.031250,34103.652344,34103.652344,92041216
2021-06-08 00:15:00+01:00,34064.179688,34077.378906,33692.035156,33814.265625,33814.265625,196007936
2021-06-08 00:30:00+01:00,33831.917969,33956.003906,33660.097656,33723.566406,33723.566406,427208704
2021-06-08 00:45:00+01:00,33708.160156,33774.433594,33480.640625,33560.707031,33560.707031,257032192
2021-06-08 01:00:00+01:00,33589.519531,34007.714844,33589.519531,34007.714844,34007.714844,635789312
...,...,...,...,...,...,...
2021-07-07 17:30:00+01:00,34584.613281,34621.632812,34548.843750,34614.406250,34614.406250,75216896
2021-07-07 17:45:00+01:00,34609.148438,34614.394531,34555.230469,34555.230469,34555.230469,8630272
2021-07-07 18:00:00+01:00,34575.453125,34593.410156,34541.027344,34583.425781,34583.425781,1742848
2021-07-07 18:15:00+01:00,34595.750000,34595.750000,34595.750000,34595.750000,34595.750000,116736
2021-07-07 18:16:02+01:00,34586.753906,34586.753906,34586.753906,34586.753906,34586.753906,0

In [22]:
ETH_price = yf.download(tickers='ETH-USD', period = '30d', interval = '15m')
ETH_price

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-06-08 00:00:00+01:00,2629.983398,2632.367432,2620.762939,2621.865723,2621.865723,103510016
2021-06-08 00:15:00+01:00,2621.151367,2621.910889,2590.242920,2605.875732,2605.875732,136361984
2021-06-08 00:30:00+01:00,2606.758301,2623.115723,2594.642090,2599.746094,2599.746094,344858624
2021-06-08 00:45:00+01:00,2597.510010,2606.651855,2583.995117,2590.263184,2590.263184,344377344
2021-06-08 01:00:00+01:00,2594.602295,2614.897705,2592.899902,2614.897705,2614.897705,280948736
...,...,...,...,...,...,...
2021-07-07 17:30:00+01:00,2349.554443,2357.774414,2344.698242,2356.051514,2356.051514,122236928
2021-07-07 17:45:00+01:00,2354.927490,2355.271240,2351.393555,2351.804199,2351.804199,41723904
2021-07-07 18:00:00+01:00,2353.089355,2356.375977,2348.625732,2356.375977,2356.375977,73621504
2021-07-07 18:15:00+01:00,2356.290527,2356.290527,2356.290527,2356.290527,2356.290527,1875968
2021-07-07 18:16:02+01:00,2355.642090,2355.642090,2355.642090,2355.642090,2355.642090,0

In [23]:
Binance_price = yf.download(tickers='BNB-USD', period = '30d', interval = '15m')
Binance_price

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-06-08 00:00:00+01:00,366.566528,366.566528,364.370239,364.712555,364.712555,780032
2021-06-08 00:15:00+01:00,364.510895,364.510895,356.440857,359.549377,359.549377,4851712
2021-06-08 00:30:00+01:00,360.274323,362.662292,358.408569,359.083435,359.083435,41753856
2021-06-08 00:45:00+01:00,358.649536,359.665894,356.362518,357.310211,357.310211,23969024
2021-06-08 01:00:00+01:00,358.165436,364.749878,358.165436,364.376404,364.376404,73484288
...,...,...,...,...,...,...
2021-07-07 17:15:00+01:00,333.870483,335.193542,333.678040,334.968689,334.968689,8999936
2021-07-07 17:30:00+01:00,334.916901,336.124786,334.152618,335.828369,335.828369,8669056
2021-07-07 17:45:00+01:00,335.486694,335.486694,334.412506,334.685486,334.685486,2832768
2021-07-07 18:00:00+01:00,334.336517,335.244232,334.252930,335.233093,335.233093,2008064
2021-07-07 18:15:09+01:00,335.353149,335.353149,335.353149,335.353149,335.353149,0

In [24]:
Cardano_price = yf.download(tickers='ADA-USD', period = '30d', interval = '15m')
Cardano_price

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-06-08 00:00:00+01:00,1.602991,1.602991,1.595099,1.595099,1.595099,4180480
2021-06-08 00:15:00+01:00,1.594053,1.594053,1.564731,1.577842,1.577842,20972288
2021-06-08 00:30:00+01:00,1.578592,1.591110,1.569368,1.569368,1.569368,44419072
2021-06-08 00:45:00+01:00,1.567236,1.572473,1.557106,1.564106,1.564106,59531264
2021-06-08 01:00:00+01:00,1.567051,1.591727,1.566706,1.591692,1.591692,47673856
...,...,...,...,...,...,...
2021-07-07 17:15:00+01:00,1.422346,1.426267,1.420543,1.425640,1.425640,16591104
2021-07-07 17:30:00+01:00,1.425391,1.426791,1.422600,1.424992,1.424992,1630976
2021-07-07 17:45:00+01:00,1.425117,1.425117,1.422768,1.422768,1.422768,4085888
2021-07-07 18:00:00+01:00,1.421170,1.423472,1.421104,1.423472,1.423472,4903680
2021-07-07 18:15:22+01:00,1.423261,1.423261,1.423261,1.423261,1.423261,0

In [25]:
XRP_price = yf.download(tickers='XRP-USD', period = '30d', interval = '15m')
XRP_price

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-06-08 00:00:00+01:00,0.874393,0.874393,0.868987,0.868987,0.868987,8439808
2021-06-08 00:15:00+01:00,0.868443,0.868443,0.853520,0.860674,0.860674,22110464
2021-06-08 00:30:00+01:00,0.861269,0.868630,0.858417,0.860605,0.860605,53798400
2021-06-08 00:45:00+01:00,0.860591,0.863451,0.856627,0.861155,0.861155,35577344
2021-06-08 01:00:00+01:00,0.862781,0.872142,0.861494,0.870616,0.870616,10682368
...,...,...,...,...,...,...
2021-07-07 17:30:00+01:00,0.663289,0.664199,0.662404,0.663798,0.663798,1459584
2021-07-07 17:45:00+01:00,0.663603,0.663603,0.662737,0.662816,0.662816,7655296
2021-07-07 18:00:00+01:00,0.663100,0.663688,0.662467,0.663332,0.663332,395392
2021-07-07 18:15:00+01:00,0.664058,0.664058,0.663860,0.663860,0.663860,1386112
2021-07-07 18:17:03+01:00,0.663493,0.663493,0.663493,0.663493,0.663493,0

In [26]:
Doge_price = yf.download(tickers='DOGE-USD', period = '30d', interval = '15m')
Doge_price

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-06-08 00:00:00+01:00,0.341517,0.341517,0.339308,0.339444,0.339444,13283072
2021-06-08 00:15:00+01:00,0.339067,0.339093,0.332408,0.334313,0.334313,25136128
2021-06-08 00:30:00+01:00,0.334465,0.337699,0.332930,0.332930,0.332930,65392384
2021-06-08 00:45:00+01:00,0.333196,0.333828,0.329806,0.331050,0.331050,78666496
2021-06-08 01:00:00+01:00,0.331822,0.336991,0.331822,0.336991,0.336991,66791424
...,...,...,...,...,...,...
2021-07-07 17:30:00+01:00,0.231150,0.231734,0.230720,0.231692,0.231692,1915200
2021-07-07 17:45:00+01:00,0.231615,0.231674,0.231225,0.231537,0.231537,2509056
2021-07-07 18:00:00+01:00,0.231526,0.231562,0.231181,0.231400,0.231400,1517632
2021-07-07 18:15:00+01:00,0.231698,0.231698,0.231698,0.231698,0.231698,0
2021-07-07 18:16:54+01:00,0.231602,0.231602,0.231602,0.231602,0.231602,0

In [27]:
Polkadot_price = yf.download(tickers='DOT1-USD', period = '30d', interval = '15m')
Polkadot_price

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-06-08 00:00:00+01:00,22.433407,22.439501,22.259115,22.353653,22.353653,11315200
2021-06-08 00:15:00+01:00,22.331835,22.331835,21.468212,21.775135,21.775135,20401536
2021-06-08 00:30:00+01:00,21.848423,22.118633,21.581240,21.626844,21.626844,36612480
2021-06-08 00:45:00+01:00,21.581852,21.742771,21.432226,21.626959,21.626959,30998400
2021-06-08 01:00:00+01:00,21.703253,22.243534,21.703253,22.243534,22.243534,47799040
...,...,...,...,...,...,...
2021-07-07 17:30:00+01:00,16.941786,16.964655,16.885611,16.949100,16.949100,5849984
2021-07-07 17:45:00+01:00,16.939625,16.961020,16.913219,16.934652,16.934652,2610432
2021-07-07 18:00:00+01:00,16.953093,16.953093,16.856617,16.878170,16.878170,736512
2021-07-07 18:15:00+01:00,16.872416,16.872416,16.867840,16.867840,16.867840,0
2021-07-07 18:17:07+01:00,16.851011,16.851011,16.851011,16.851011,16.851011,0

In [28]:
Uniswap_price = yf.download(tickers='UNI3-USD', period = '30d', interval = '15m')
Uniswap_price

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-06-08 00:00:00+01:00,24.631714,24.631714,24.429756,24.463215,24.463215,5347648
2021-06-08 00:15:00+01:00,24.422722,24.439436,24.071053,24.322834,24.322834,4359296
2021-06-08 00:30:00+01:00,24.317917,24.570383,24.110182,24.173126,24.173126,7947424
2021-06-08 00:45:00+01:00,24.169737,24.302053,24.011368,24.195166,24.195166,4321728
2021-06-08 01:00:00+01:00,24.277176,24.585096,24.277176,24.585096,24.585096,8069984
...,...,...,...,...,...,...
2021-07-07 17:30:00+01:00,22.748835,22.901649,22.692881,22.899458,22.899458,4631424
2021-07-07 17:45:00+01:00,22.901325,22.901325,22.806337,22.806337,22.806337,1103488
2021-07-07 18:00:00+01:00,22.751144,22.868544,22.751144,22.868544,22.868544,179392
2021-07-07 18:15:00+01:00,22.856869,22.856869,22.856869,22.856869,22.856869,0
2021-07-07 18:17:13+01:00,22.802652,22.802652,22.802652,22.802652,22.802652,0

In [29]:
Solana_price = yf.download(tickers='SOL1-USD', period = '30d', interval = '15m')
Solana_price

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-06-08 00:00:00+01:00,40.240448,40.240448,40.006443,40.033058,40.033058,66944
2021-06-08 00:15:00+01:00,40.021255,40.021255,38.772396,39.269131,39.269131,6115264
2021-06-08 00:30:00+01:00,39.269459,39.781597,38.823711,38.823711,38.823711,14358656
2021-06-08 00:45:00+01:00,38.679008,38.855152,38.090839,38.262333,38.262333,19177792
2021-06-08 01:00:00+01:00,38.251270,39.521675,38.251270,39.521675,39.521675,24756736
...,...,...,...,...,...,...
2021-07-07 17:30:00+01:00,36.624706,36.742634,36.389008,36.704853,36.704853,3582592
2021-07-07 17:45:00+01:00,36.700489,36.700489,36.529907,36.563148,36.563148,1009824
2021-07-07 18:00:00+01:00,36.569778,36.647766,36.422329,36.647766,36.647766,2003776
2021-07-07 18:15:00+01:00,36.629726,36.629726,36.561665,36.561665,36.561665,0
2021-07-07 18:17:05+01:00,36.603577,36.603577,36.603577,36.603577,36.603577,0

In [30]:
BTC_cash_price = yf.download(tickers='BCH-USD', period = '30d', interval = '15m')
BTC_cash_price

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-06-08 00:00:00+01:00,611.161133,611.161133,607.905396,607.928650,607.928650,3639296
2021-06-08 00:15:00+01:00,607.229187,607.229187,598.800537,600.821960,600.821960,5746304
2021-06-08 00:30:00+01:00,603.795837,606.801880,599.516052,599.872864,599.872864,27161216
2021-06-08 00:45:00+01:00,598.890625,599.239197,594.236023,596.077881,596.077881,27718656
2021-06-08 01:00:00+01:00,596.839417,603.685852,594.703491,603.685852,603.685852,22263296
...,...,...,...,...,...,...
2021-07-07 17:30:00+01:00,523.255798,523.865234,522.210327,523.660828,523.660828,3121024
2021-07-07 17:45:00+01:00,523.612671,523.612671,521.763733,521.872375,521.872375,8383104
2021-07-07 18:00:00+01:00,521.390015,521.530090,520.786865,521.465454,521.465454,53760
2021-07-07 18:15:00+01:00,521.545349,521.545349,521.545349,521.545349,521.545349,62976
2021-07-07 18:17:12+01:00,521.126953,521.126953,521.126953,521.126953,521.126953,0